### PR TITLE
Port to Qt6

### PR DESCRIPTION
**Pull request by timsurber**
This ports to Qt6.

There are some additional whitespace changes and a editorconfig file is added.

Works already on Linux, still have to test Windows

### CODE REVIEW

**Comment by rumengb** [comment]
This is on linux:

../common_src/imageviewer.h:126:14: error: ‘void ImageViewer::enterEvent(QEnterEvent*)’ marked ‘override’, but does not override
  126 |         void enterEvent(QEnterEvent *event) override;
      |              ^~~~~~~~~~

**Comment by timsurber** [comment]
I had the same issue and could fix it by running `qmake6`  `make clean` `make`

**Comment by rumengb** [comment]
And please split whitespace changes to another commit. please keep commits clean so that it is easier to review.

Also please make the PR to the at6_port branch i merged your commit there

**Comment by rumengb** [comment]
> I had the same issue and could fix it by running `qmake6` `make clean` `make`

This is exactly what i did

**Comment by timsurber** [comment]
I just looked at my command line history. I also deleted the main makefile and the generated sub-makefiles first. In the build log, there should all qt5 instances replaced by qt6 when it works.

If this doesn't solve your issue, I will investigate on fresh system.

**Comment by rumengb** [comment]
after deleting the three makefiles:

/usr/bin/ld: object/moc_qindigoservers.o: in function `QtPrivate::QMetaTypeForType<QIndigoService>::getCopyCtr()::{lambda(QtPrivate::QMetaTypeInterface const*, void*, void const*)#1}::operator()(QtPrivate::QMetaTypeInterface const*, void*, void const*) const':
/usr/include/x86_64-linux-gnu/qt6/QtCore/qmetatype.h:2262: undefined reference to `QIndigoService::QIndigoService(QIndigoService const&)'
/usr/bin/ld: object/moc_qindigoservers.o: in function `QtPrivate::QMetaTypeForType<QIndigoService>::getMoveCtr()::{lambda(QtPrivate::QMetaTypeInterface const*, void*, void*)#1}::operator()(QtPrivate::QMetaTypeInterface const*, void*, void*) const':
/usr/include/x86_64-linux-gnu/qt6/QtCore/qmetatype.h:2273: undefined reference to `QIndigoService::QIndigoService(QIndigoService const&)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.ain_imager:296: ain_imager] Error 1
make[1]: Leaving directory '/home/rumen/work/indigo_imager.git/ain_imager_src'
make: *** [Makefile:48: sub-ain_imager_src-ain_imager-pro-make_first] Error 2

**Comment by timsurber** [comment]
I'm not sure why this is happening, I guess some caching issue?

Here you can see a build script for github actions which builds successfully the binaries: (I think this would be a nice addition too)

https://github.com/timsurber/indigo_imager/blob/port-qt6-ci/.github/workflows/build_linux.yml

**Comment by rumengb** [comment]
> I'm not sure why this is happening, I guess some caching issue?
> 
> Here you can see a build script for github actions which builds successfully the binaries: (I think this would be a nice addition too)
> 
> https://github.com/timsurber/indigo_imager/blob/port-qt6-ci/.github/workflows/build_linux.yml

Thank you for your effort! :)
I see the problem - you use Ubuntu 24.04. 

Ain is supported on multiple architectures and it currently works on Debian Bullseye and Bookworm Ubuntu 22.04 LTS on Intel 32 and 64. and arm 32 and 64. None of the docker builds succeed, failing with different errors :( I even tried it on arm bookworm and it does not compile too. It only works on Ubuntu 24.04. 

Please make sure it builds on these platforms: 
i386/debian:bullseye
amd64/debian:bullseye
arm32v7/debian:bullseye
arm64v8/debian:bullseye

I hope you understand - nothing personal, but I can not switch to qt6 if it does not compile and work reliably on all supported platforms and and I can not support two versions of Ain one for qt6 and one for qt5. And the current port does not work on ARM at all and I guess it will not work on Bookworm on Intel too not to mention Bullseye...

So I guess the qt6_port branch will stay for some time and I will switch to qt6 once I am convinced it works as good as qt5 version :)

**Comment by timsurber** [comment]
Of course, I fully understand that it still needs quite a bit polishing.

Would you agree to **dropping 32 bit support**?

Qt6 dropped support 4 years ago, (which is kind of a blocker, even if there are inofficial solutions) Microsoft did it also 4 years ago for Windows, Ubuntu 5 years ago, Debian will in the next release.

I think for desktops it would be no issue at all dropping it, you already have almost no support in other applications.

For ARM there is something like the Raspberry Pi 2 which is now also 9 years old, which only supports 32 bit.
And I think the typical usecase for those small ARM Boards is running indigo_server, not the client software.

I would work on making sure it builds on amd64 windows, amd64 linux, arm64 linux.
Debian bullseye has Qt6 in backports, so I should get it to work.

But I think we should still target Qt6 in the future, because of bug fixes, security issues and new features (for example better wayland support and support of high resolution screens).


Edit: Debian still has 32 bit builds for Qt6 available, so this should still work but it would be nice to drop 32 bit.

**Comment by rumengb** [comment]
I was thinking of dropping 32-bit support for Windows and I will happily do this. 

But believe it or not, we still have users who use core2 processors on Debian which are not capable of running 64-bit OS. And rpi3s and 4s with 1 GB are not enough for a 64-bit OS. So I would still keep 32-bit Arm support for at least a year.

Also, Bookworm will be supported until June 2028. Another thing is that we still do not have 64-bit arm support for some hardware (as far as I remember) in Indigo as the vendors still do not provide Arm64 SDK. And users often run Ain with indigo on the same host. So it is a bit early to drop 32-bit support altogether.

For the time being the only safe platform to drop 32-bit support is Windows as we do not provide indigo drivers for Windows. It is ok to some extent for intel Linux. But not for arm.

And yes I agree we should move to qt6 but not at all costs :)

**Comment by timsurber** [comment]
The build error you encountered on ubuntu 22.04 (and I could reproduce) is not related to Qt6 but a coincidence that just surfaced now, was probably optimized out by the compiler before.

https://github.com/indigo-astronomy/indigo_imager/blob/fff2b43f6f34c50894a883b21c9ea37e9bb1132d/ain_imager_src/qindigoservice.h#L30C2-L30C46

Here you declare a copy constructor but provide no implementation in the .cpp file.

What do you meant to do there? Delete the copy constructor or use the default implementation?
